config/routes.rb
RailsExercise::Application.routes.draw do

  devise_for :authors

  resources :articles
  root :to => "articles#index"
  resources :articles do
    resources :comments #, :except => [:edit, :update]
  end
  resources :authors

  match ':controller(/:action(/:id(.:format)))'

end

app/models/comment.rb
# == Schema Information
# Schema version: 20110524014116
#
# Table name: comments
#
#  id           :integer(4)      not null, primary key
#  email        :string(255)
#  body         :text
#  comment_date :datetime
#  article_id   :integer(4)
#  created_at   :datetime
#  updated_at   :datetime
#

class Comment < ActiveRecord::Base
  
  sort_record_by 'id'
  validates_presence_of :email
  validates_presence_of :body
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  belongs_to :article, :foreign_key => "article_id"
  before_create :date_comment

  def date_comment
    self.comment_date = Time.now.strftime("%Y-%m-%d %I:%M")
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_filter :get_article 
  before_filter :authenticate_author!, :except => [:index, :show, :new, :create]

  def index
    @comments = @article.comments.paginate :page => params[:page], :per_page => 5, :order => "updated_at DESC"
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.xml  { render :xml => @comments }
    end
  end

  def show
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  def new
    @comment = Comment.new
    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.xml  { render :xml => @comments }
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.article_id = (params[:article_id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(article_comment_path(@comment.article_id, @comment), :notice => 'comment was successfully created.') }
        format.js
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(article_comment_path(@article, @comment), :notice => 'comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(article_path(@article)) }
      format.xml  { head :ok }
    end
  end

private
  def get_article
    @article = Article.find(params[:article_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if author_signed_in? %>
    <%= f.hidden_field :email, :value => current_author.email %>
  <% else %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_area :body, :id => "comment_txtArea" %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Add Comment"%>
  </div>

app/views/comments/_index.html.erb
<hr />
<h1>Comments</h1>
<hr />
<ul id="comments_ul">
<% comments.each do |comment| %>
  <li class="comment_list">
    <% authors = Author.all %>
    <% authors.each do |author| %> 
      <%= image_tag author.photo.url(:thumb), :size => "30x30" if author.email == comment.email %>
    <% end %>
    <%= link_to comment.email, article_comment_path(@article, comment), :id => "comment-#{comment.id}" %> &raquo; 
    <span class="time"><%= time_ago_in_words(comment.created_at) %> ago</span>
    <ul>
      <li><p class="comments"><%= comment.body %></p></li>
    </ul>
  </li>
<% end %>
</ul>
 
<br />

<%= link_to 'Add Comment', new_article_comment_path(@article), :id => "addCommentlnk", :remote => true %> |
<%= link_to "Hide Comments", "#", :id => "hide" %>

<div id="addComment">

</div>

app/views/comments/_new.html.erb
<hr />
<% form_for @comment, :url => article_comments_path(@article), :remote => true do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>
<hr />
<%= link_to "Hide Form", "#comments_content", :id => "hideForm" %>

app/views/comments/create.js.erb
$("#comments_ul li.comment_list:last").hide();
$("#comments_content").html("<%= escape_javascript(render :partial => 'comments/index', :locals => {:comments => @article.comments})%>").show('slow');
$("#comments_ul li.comment_list:last").hide().fadeIn(1000);
$("#commlistlnk").html("Comments (<%= @article.comments.size %>)");

app/views/comments/edit.html.erb
<h1>Editing Article</h1>
<hr />
<% form_for @comment, :url => article_comment_path(@article, @comment) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>
<hr />
<%= link_to 'Show', @article %> |
<%= link_to 'Back', article_comments_path(@article) %>

app/views/comments/index.html.erb
<h1>Comments</h1>
<hr />
<ul>
<% @comments.each do |comment| %>
  <li>
    <%= link_to comment.email, article_comment_path(@article, comment), :id => "comment-#{comment.id}" %>
    <ul>
      <li><%= comment.body.truncate(10)%></li>
    </ul>
  </li>
<% end %>
</ul>
<%= will_paginate @comments %>  
<br />

<%= link_to 'New Comment', new_article_comment_path %> |
<%= link_to "Back to '#{@article.title}'", @article  %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<hr />
<% form_for @comment, :url => article_comments_path(@article) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>
<hr />
<%= link_to 'Back', article_path(@article) %>

app/views/comments/new.js.erb
$("#addComment").html("<%= escape_javascript(render :partial => 'comments/new')%>").hide().show(1000);

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @comment.email%>
</p>

<b>Comment:</b>
<p class="comments">
  <%= @comment.body%>
</p>

<p>
  <b>Comment Date:</b>
  <%= @comment.comment_date%>
</p>

<% if author_signed_in? and @comment.email == current_author.email %>
  <%= link_to 'Edit', edit_article_comment_path(@article, @comment) %> |
<% end %>
<% if current_author == @article.author %>
  <%= link_to 'Delete', article_comment_path(@article, @comment), :method => :delete, :confirm => "Are you sure?" %> |
<% end %>
<%= link_to 'Back', article_path(@article) %>