config/routes.rb
RailsExercise::Application.routes.draw do

  devise_for :authors

  resources :articles
  root :to => "articles#index"
  resources :articles do
    resources :comments #, :except => [:edit, :update]
  end
  resources :authors

  match ':controller(/:action(/:id(.:format)))'

end

app/models/article.rb
# == Schema Information
# Schema version: 20110524014116
#
# Table name: articles
#
#  id          :integer(4)      not null, primary key
#  title       :string(255)
#  body        :text
#  status      :text
#  date_posted :datetime
#  author_id   :integer(4)
#  created_at  :datetime
#  updated_at  :datetime
#

class Article < ActiveRecord::Base
  
  cattr_reader :per_page
    @@per_page = 5
  sort_record_by 'date_posted'
  validates_presence_of :title
  validates_presence_of :body
  validates_inclusion_of :status, :in => %w( Draft Posted )
  
  belongs_to :author, :foreign_key => "author_id"
  has_many :comments, :dependent => :delete_all
  
  before_save :fill_date

  def fill_date
    self.date_posted = Time.now.strftime("%Y-%m-%d %I:%M") if self.status.downcase.eql?("posted")
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.paginate :page => params[:page], :order => 'updated_at DESC'
    respond_to do |format|
      format.html # index.html.erb
      format.xml  #{ render :xml => @articles }
    end
  end

  def show
    @article = Article.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.xml  { render :xml => @articles }
    end
  end

  def new
    @article = Article.new
    @authors = Author.all
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @articles }
    end
  end
  
  def edit
    @article = current_author.articles.find(params[:id])
    #@authors = Author.all
  end

  def create
    #@article = Article.new(params[:article])
    #@authors = Author.all
    @article = current_author.articles.build(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    #@article = Article.find(params[:id])
    #@authors = Author.all
    @article = current_author.articles.find(params[:id])
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

    
  <%= f.hidden_field :author_id %>
  

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :id => "article_txtArea"  %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select(:status, options_for_select([["Draft","Draft"], ["Posted", "Posted"]])) %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>
<hr />
<%= render 'form' %>
<hr />
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<hr />
<ul>
<% @articles.each do |article| %>
  <% if article.status == "Posted" or article.author == current_author %>
  <li title="<%= article.author.full_name %>" class="lists">
    &raquo; <%= link_to article.title, article %> 
    <span class="draft"><%= "(Draft)" unless article.status == "Posted" %></span>
    <ul>
      <li><%= article.body.truncate(10)%></li>
    </ul>
  </li>
  <% end %>
<% end %>
</ul>
<%= will_paginate @articles %>

<% if author_signed_in? %>
<br />
<%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<hr />
<%= render 'form' %>
<hr />
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @article.title %>
</h1>

<p id="article_body">
  <%= @article.body%>
</p>

<p>
<%= @article.status %> by:
  <%= link_to (image_tag @article.author.photo.url(:thumb), :size => "30x30"), author_path(@article.author), :id => "imglnk" %> 
  <%= @article.author.full_name %>
</p>

<p>
  <%= @article.date_posted %>
</p>

<%= link_to "Comments (#{@article.comments.size})", article_path(@article), :remote => true, :id => "commlistlnk" %> |
<% if current_author == @article.author %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), :method => :delete, :confirm => "Are you sure?" %> |
<% end %>
<%= link_to 'Back to Articles', articles_path %>

<div id="comments_content">

</div>

app/views/articles/show.js.erb
$("#comments_content").html("<%= escape_javascript(render :partial => 'comments/index', :locals => {:comments => @article.comments})%>").hide().show(1000);