config/routes.rb
RailsExercise::Application.routes.draw do

  devise_for :authors

  resources :articles
  root :to => "articles#index"
  resources :articles do
    resources :comments #, :except => [:edit, :update]
  end
  resources :authors

  match ':controller(/:action(/:id(.:format)))'

end

app/models/author.rb
# == Schema Information
# Schema version: 20110524014116
#
# Table name: authors
#
#  id         :integer(4)      not null, primary key
#  last_name  :string(255)
#  first_name :string(255)
#  remarks    :text
#  birthday   :date
#  created_at :datetime
#  updated_at :datetime
#

class Author < ActiveRecord::Base

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "50x50>" }, :default_url => "./no-image.jpeg"
  #default_scope order('last_name, first_name')
  sort_record_by 'last_name, first_name'
  #attr_accessor :photo_file_name
  #attr_accessor :photo_content_type
  #attr_accessor :photo_file_size
  #attr_accessor :photo_updated_at

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :remarks, :birthday, :photo
  cattr_reader :per_page
    @@per_page = 5

  validates_presence_of :last_name
  validates_presence_of :first_name

  has_many :articles, :dependent => :delete_all

  def full_name
    "#{last_name}, #{first_name}"
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.paginate :page => params[:page], :order => 'updated_at ASC'
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @authors }
    end
  end

  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @authors }
    end
  end

  def new
    @author = Author.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @authors }
    end
  end
  
  def edit
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(params[:author])
    #@author.photo = params[:photo]
    respond_to do |format|
      if @author.save
        format.html { redirect_to(@author, :notice => 'Author was successfully created.') }
        format.xml  { render :xml => @author, :status => :created, :location => @author }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @author = Author.find(params[:id])
    #@author.photo= params[:photo]
    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to(@author, :notice => 'author was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to(authors_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for @author, :html => {:multipart => true} do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name%>
  </div>
  <div class="field">
    <%= f.label :remarks%><br />
    <%= f.text_area :remarks%>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select("birthday", :order => [:day, :month, :year], :start_year => 1980, :end_year => Time.now.year - 12) %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %><br />
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>
<hr />
<%= render 'form' %>
<hr />
<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>
<hr />
<ul>
<% @authors.each do |author| %>
  <li class="lists">
    <%= image_tag author.photo.url(:thumb), :size => "50x50" %>  
    <%= link_to author.full_name, author %>
    <span class="you"><%= "(You!)" if current_author == author %></span>
  </li>
<% end %>
</ul>
<%= will_paginate @authors %>

<% if !author_signed_in? %>
<br />
<%= link_to 'New Author', new_author_registration_path %>
<% end %>

app/views/authors/new.html.erb
<h1>New Author</h1>
<hr />
<%= render 'form' %>
<hr />
<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<div id="wrapper">
<div id="imagePanel">
<%= image_tag @author.photo.url(:medium) %>
</div>
<div id="authorInfo">
<p>
  <b><%= @author.full_name %></b>
</p>

<p>
  <b>Remarks:</b>
  <%= @author.remarks%>
</p>

<p>
  <b>Birthday:</b>
  <%= @author.birthday%>
</p>

<p>
  <b><%= "Articles:" if @author.articles.size > 0 %></b>
  <ul>
  <% @author.articles.each do |article|%>
     <% if article.status == "Posted" or article.author == current_author %>
     <li title="<%= article.body.truncate(30) %>">&raquo; <%= link_to article.title, article_path(article) %>
        <span class="draft"><%= "(Draft)" unless article.status == "Posted" %></span>
     </li>
     <% end %>
  <%end%>
  
  </ul>
</p>
</div>
</div>
<div class="clear"></div>
<% if current_author == @author %>
<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Delete', author_path(@author), :method => :delete, :confirm => "Are you sure?" %> |
<% end %>
<%= link_to 'Back to Authors', authors_path %>